baseurl = "http://labargewedding.com"
title = "LaBarge Wedding"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Dimension"
  description = 'You are invited to celebrate the marriage of <strong>Jessica Palmieri</strong> and <strong>Christopher LaBarge</strong>.<br />
                 <!--[-->September 30th, 2017 at the <a target="_blank" href="https://www.google.com/search?q=new+york+state+museum&oq=new+york">New York State Museum</a>.<!--]-->'
  logo = "fa-heart"
  copyright = "Untitled"
  class = "no-photoswipe"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[figure]
  class = "no-photoswipe"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "LaBarge Wedding"

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Dimension"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
